In [9]:
import numpy as np
import pandas as pd

# --- Step 1: Define Vocabulary and Tokenization ---
# Our sample vocabulary
vocabulary = ['the', 'cat', 'sat', 'on', 'the', 'mat', 'quickly', 'jumped']

# Create a mapping from word to unique integer ID
word_to_id = {word: i for i, word in enumerate(sorted(list(set(vocabulary))))}
id_to_word = {i: word for word, i in word_to_id.items()}

print("--- Step 1: Vocabulary and Token IDs ---")
print("Word to ID mapping:", word_to_id)
print("ID to Word mapping:", id_to_word)

# Example word and its token ID
word = 'cat'
token_id = word_to_id.get(word, -1) # Use .get() to handle words not in vocab
print(f"\nWord '{word}' corresponds to Token ID: {token_id}")

--- Step 1: Vocabulary and Token IDs ---
Word to ID mapping: {'cat': 0, 'jumped': 1, 'mat': 2, 'on': 3, 'quickly': 4, 'sat': 5, 'the': 6}
ID to Word mapping: {0: 'cat', 1: 'jumped', 2: 'mat', 3: 'on', 4: 'quickly', 5: 'sat', 6: 'the'}

Word 'cat' corresponds to Token ID: 0

In [10]:
# --- Step 2: From Token ID to a d-dimensional Feature Vector (Embedding) ---
# Define the embedding dimension (d)
embedding_dim = 5

print("\n--- Step 2: Individual Embeddings (d-dimensional Feature Vectors) ---")

# Store individual embeddings in a dictionary
individual_embeddings = {}
for word, token_id in word_to_id.items():
    # Generate a random vector for each token ID
    # np.random.rand() generates values between 0 and 1. We scale and shift them.
    embedding = (np.random.rand(embedding_dim) * 2 - 1) # Values between -1 and 1
    individual_embeddings[token_id] = embedding
    print(f"Token ID {token_id} ('{word}'): {embedding.round(3)}")

# Example: Embedding for 'cat' (Token ID 1)
if token_id != -1:
    cat_embedding = individual_embeddings.get(token_id)
    print(f"\nEmbedding for '{word}' (Token ID {token_id}): {cat_embedding.round(3)}")
else:
    print(f"Word '{word}' not found in vocabulary.")

--- Step 2: Individual Embeddings (d-dimensional Feature Vectors) ---
Token ID 0 ('cat'): [-0.256  0.812  0.073 -0.084 -0.7  ]
Token ID 1 ('jumped'): [ 0.011 -0.984 -0.252 -0.31  -0.559]
Token ID 2 ('mat'): [ 0.023 -0.93  -0.187  0.704  0.509]
Token ID 3 ('on'): [ 0.332 -0.874 -0.66   0.721  0.273]
Token ID 4 ('quickly'): [ 0.263 -0.228  0.016  0.308 -0.893]
Token ID 5 ('sat'): [ 0.368 -0.974  0.193 -0.179 -0.423]
Token ID 6 ('the'): [ 0.99  -0.808  0.739 -0.259 -0.049]

Embedding for 'the' (Token ID 6): [ 0.99  -0.808  0.739 -0.259 -0.049]

In [11]:
# --- Step 3: Stacking to Form the Embedding Matrix ---
# Get the size of the vocabulary (V)
vocab_size = len(word_to_id)

# Create an empty matrix to hold all embeddings
# The shape will be (vocab_size, embedding_dim)
embedding_matrix = np.zeros((vocab_size, embedding_dim))

# Fill the embedding matrix using the token IDs as indices
print("\n--- Step 3: Constructing the Embedding Matrix ---")
for token_id, embedding_vector in individual_embeddings.items():
    embedding_matrix[token_id] = embedding_vector

print(f"Embedding Matrix Shape: {embedding_matrix.shape} (Vocabulary Size x Embedding Dimension)\n")

# Display the embedding matrix using a Pandas DataFrame for better readability
# The index will be the Token IDs, and columns can be 'Dim_0', 'Dim_1', etc.
embedding_df = pd.DataFrame(embedding_matrix,
                            index=[id_to_word[i] for i in range(vocab_size)],
                            columns=[f'Dim_{i}' for i in range(embedding_dim)])

print("Embedding Matrix:")
display(embedding_df.round(3))

--- Step 3: Constructing the Embedding Matrix ---
Embedding Matrix Shape: (7, 5) (Vocabulary Size x Embedding Dimension)

Embedding Matrix:

         Dim_0  Dim_1  Dim_2  Dim_3  Dim_4
cat     -0.256  0.812  0.073 -0.084 -0.700
jumped   0.011 -0.984 -0.252 -0.310 -0.559
mat      0.023 -0.930 -0.187  0.704  0.509
on       0.332 -0.874 -0.660  0.721  0.273
quickly  0.263 -0.228  0.016  0.308 -0.893
sat      0.368 -0.974  0.193 -0.179 -0.423
the      0.990 -0.808  0.739 -0.259 -0.049

In [12]:

if 'word_to_id' not in locals():
    vocabulary = ['the', 'cat', 'sat', 'on', 'the', 'mat', 'quickly', 'jumped']
    word_to_id = {word: i for i, word in enumerate(sorted(list(set(vocabulary))))}
    id_to_word = {i: word for word, i in word_to_id.items()}

if 'embedding_dim' not in locals():
    embedding_dim = 5

if 'individual_embeddings' not in locals():
    individual_embeddings = {}
    for word, token_id in word_to_id.items():
        embedding = (np.random.rand(embedding_dim) * 2 - 1)
        individual_embeddings[token_id] = embedding

print("--- Step 4: Implementing Positional Encoding ---")

def positional_encoding(position, d_model):
    """
    Calculates the positional encoding for a given position and embedding dimension.
    PE(pos, 2i) = sin(pos / 10000^(2i/d_model))
    PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))
    """
    pe = np.zeros(d_model)
    for i in range(d_model):
        if i % 2 == 0: # Even dimensions
            pe[i] = np.sin(position / (10000 ** (i / d_model)))
        else: # Odd dimensions
            pe[i] = np.cos(position / (10000 ** ((i - 1) / d_model)))
    return pe

# --- Step 5: Apply Positional Encoding to a Sequence ---
# Let's consider a sample sentence (sequence of words)
sentence = ['the', 'cat', 'sat', 'on', 'the', 'mat']

# Convert sentence words to token IDs
sentence_token_ids = [word_to_id[word] for word in sentence if word in word_to_id]

print(f"\nSample Sentence: {sentence}")
print(f"Token IDs for sentence: {sentence_token_ids}")

# Retrieve word embeddings for the sentence
word_embeddings_sequence = np.array([individual_embeddings[token_id] for token_id in sentence_token_ids])

# Generate positional encodings for each word in the sentence
positional_encodings_sequence = np.array([
    positional_encoding(pos, embedding_dim) for pos in range(len(sentence_token_ids))
])

print(f"\nShape of Word Embeddings for sequence: {word_embeddings_sequence.shape}")
print(f"Shape of Positional Encodings for sequence: {positional_encodings_sequence.shape}")

print("\nPositional Encodings for the sentence:")
positional_encoding_df = pd.DataFrame(positional_encodings_sequence,
                           index=[f'{word} (pos {i})' for i, word in enumerate(sentence)],
                           columns=[f'Dim_{i}' for i in range(embedding_dim)])
display(positional_encoding_df.round(3))

# --- Step 6: Combine Word Embeddings and Positional Encodings ---
# Add the positional encodings to the word embeddings
# This is a common way to inject position information into the embeddings
combined_embeddings = word_embeddings_sequence + positional_encodings_sequence

print("\nCombined Embeddings (Word Embedding + Positional Encoding) for the sentence:")
combined_df = pd.DataFrame(combined_embeddings,
                           index=[f'{word} (pos {i})' for i, word in enumerate(sentence)],
                           columns=[f'Dim_{i}' for i in range(embedding_dim)])
display(combined_df.round(3))

print("\n--- Explanation ---")
print("1. The `positional_encoding` function generates a vector where odd and even dimensions are filled with sine and cosine functions, respectively, based on the word's position and the embedding dimension.")
print("2. For a given sentence, we get the word embeddings for each token.")
print("3. We then generate a corresponding positional encoding for each position (0, 1, 2, ...).")
print("4. Finally, these positional encodings are simply added to their respective word embeddings. This sum is the new, position-aware embedding for each word in the sequence.")

--- Step 4: Implementing Positional Encoding ---

Sample Sentence: ['the', 'cat', 'sat', 'on', 'the', 'mat']
Token IDs for sentence: [6, 0, 5, 3, 6, 2]

Shape of Word Embeddings for sequence: (6, 5)
Shape of Positional Encodings for sequence: (6, 5)

Positional Encodings for the sentence:

             Dim_0  Dim_1  Dim_2  Dim_3  Dim_4
the (pos 0)  0.000  1.000  0.000  1.000  0.000
cat (pos 1)  0.841  0.540  0.025  1.000  0.001
sat (pos 2)  0.909 -0.416  0.050  0.999  0.001
on (pos 3)   0.141 -0.990  0.075  0.997  0.002
the (pos 4) -0.757 -0.654  0.100  0.995  0.003
mat (pos 5) -0.959  0.284  0.125  0.992  0.003

Combined Embeddings (Word Embedding + Positional Encoding) for the sentence:

             Dim_0  Dim_1  Dim_2  Dim_3  Dim_4
the (pos 0)  0.990  0.192  0.739  0.741 -0.049
cat (pos 1)  0.585  1.353  0.098  0.916 -0.699
sat (pos 2)  1.278 -1.390  0.244  0.820 -0.422
on (pos 3)   0.474 -1.864 -0.585  1.718  0.275
the (pos 4)  0.233 -1.462  0.840  0.736 -0.047
mat (pos 5) -0.936 -0.646 -0.062  1.697  0.512

--- Explanation ---
1. The `positional_encoding` function generates a vector where odd and even dimensions are filled with sine and cosine functions, respectively, based on the word's position and the embedding dimension.
2. For a given sentence, we get the word embeddings for each token.
3. We then generate a corresponding positional encoding for each position (0, 1, 2, ...).
4. Finally, these positional encodings are simply added to their respective word embeddings. This sum is the new, position-aware embedding for each word in the sequence.


1.  **Vocabulary and Token IDs**: We define a simple vocabulary and create a mapping from words to unique integer IDs. This represents the 'tokenization' step.
2.  **Individual Embeddings**: For each unique token ID, we generate a random `d`-dimensional numerical vector. In real-world applications, these vectors are learned through neural networks (e.g., Word2Vec, GloVe, BERT) to capture semantic relationships.
3.  **Embedding Matrix**: All these individual `d`-dimensional vectors are then stacked together, forming a `|V| x d` matrix. Each row in this matrix corresponds to the embedding of a specific word in our vocabulary.

This `embedding_matrix` is a fundamental component in many NLP models, allowing words to be represented as numerical data that machine learning algorithms can process.